#!/usr/bin/env python3
"""Consolidate the per-file skip-classification reports (logs/skipreport-*.json)
and the execution results (logs/results*.json) into a single machine-readable
ledger logs/skip_classification.json + a human summary printed to stdout.

Run after run_tests.py / the collect-only classification pass has populated
logs/skipreport-*.json.
"""
from __future__ import annotations
import collections
import glob
import json
import os
from pathlib import Path

HERE = Path(__file__).parent
LOGS = HERE / "logs"


def load(p):
    try:
        return json.loads(Path(p).read_text())
    except Exception:
        return None


def main():
    per_file = {}
    agg = collections.Counter()
    for fp in sorted(LOGS.glob("skipreport-*.json")):
        d = load(fp)
        if not d:
            continue
        name = fp.name.replace("skipreport-", "").replace(".json", "")
        per_file[name] = {
            "skipped_by_category": d.get("skipped_by_category", {}),
            "total_classified_inapplicable": d.get("total_classified_inapplicable", 0),
            "examples": d.get("examples", {}),
        }
        for k, v in d.get("skipped_by_category", {}).items():
            agg[k] += v

    host = load(LOGS / "results.json")
    wasm_sim = load(LOGS / "results-wasm-sim.json")

    out = {
        "_about": "Consolidated ledger: which upstream PyTorch tests are classified as fundamentally inapplicable to the reduced wasm32-emscripten torch build, by file and category. Generated by summarize.py from logs/skipreport-*.json. Execution baselines (host reference torch and simulated-wasm applicable subset) are included for context; a true wasm execution requires the built torch module (see RESULTS.md).",
        "classified_inapplicable_by_file": per_file,
        "classified_inapplicable_by_category_total": dict(agg),
        "grand_total_classified_inapplicable": sum(agg.values()),
        "execution_host_baseline": (host or {}).get("per_file"),
        "execution_wasm_simulated_applicable_subset": (wasm_sim or {}).get("per_file"),
    }
    (LOGS / "skip_classification.json").write_text(json.dumps(out, indent=2))

    print("== classified inapplicable by category ==")
    for k, v in sorted(agg.items(), key=lambda kv: -kv[1]):
        print(f"  {v:5d}  {k}")
    print(f"  {sum(agg.values()):5d}  TOTAL")
    print(f"-> {LOGS/'skip_classification.json'}")


if __name__ == "__main__":
    main()
